CC = gcc
CFLAGS = -Wall -Wextra

gradebook: main.c addStudent.c findStudent.c updateStudent.c addGrade.c deleteGrade.c listGrade.c validateInput.c
	gcc main.c addStudent.c findStudent.c updateStudent.c addGrade.c deleteGrade.c listGrade.c validateInput.c -o gradebook

clean:
    rm -f gradebook
