CC = gcc
CFLAGS = -Wall -Wextra

gradebook: addGrade.c addStudent.c deletGrade.c editGrade.c findStudent.c listGrade.c listStudent.c main.c sort.c student.c updateStudent.c validateInputs.c
	gcc addGrade.c addStudent.c deletGrade.c editGrade.c findStudent.c listGrade.c listStudent.c main.c sort.c student.c updateStudent.c validateInputs.c -o gradebook

clean:
    rm -f gradebook
